# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'capybara', '~> 3.21'
gem 'cucumber', '~> 3.1', '>= 3.1.2'
gem 'dotenv', '~> 2.7', '>= 2.7.2'
gem 'json', '~> 2.2'
gem 'mail', '~> 2.7', '>= 2.7.1'
gem 'mysql2', '~> 0.5.2'
gem 'net-ssh', '~> 5.2'
gem 'net-ssh-gateway', '~> 2.0'
gem 'os', '~> 1.0', '>= 1.0.1'
gem 'pg', '~> 1.1', '>= 1.1.4'
gem 'prawn', '~> 2.2', '>= 2.2.2'
gem 'pry', '~> 0.12.2'
gem 'rake', '~> 12.3', '>= 12.3.2'
gem 'rdoc', '~> 6.1', '>= 6.1.1'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem 'rspec', '~> 3.8'
gem 'rubyzip', '~> 1.2', '>= 1.2.3'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3'
gem 'simplecov', '~> 0.16.1'
gem 'sqlite3', '~> 1.4', '>= 1.4.1'